version: ~> 1.0
import:
  - "build.yml"
  - "deploy.yml"

language: go
go: 1.12.x

before_install:
- echo '1 .travis.yml before install'

script:
- echo '5 .travis.yml script'

deploy:
- provider: script
  script: echo '7 .travis.yml deploy'
  on:
    all_branches: true
